In [27]:
from app.collect_prices import collect_prices

In [28]:
all_prices_usd = collect_prices()

/Users/alexandre.sabino/git/fiap-tech-challenge-genetic-algorithm/app/collect_prices.py:29: FutureWarning: YF.download() has changed argument auto_adjust default to True
  prices_usa = yf.download(tickers_usa, start=start, end=end, interval='1mo')['Close']
[*********************100%***********************]  5 of 5 completed
/Users/alexandre.sabino/git/fiap-tech-challenge-genetic-algorithm/app/collect_prices.py:20: FutureWarning: YF.download() has changed argument auto_adjust default to True
  prices_br = yf.download(tickers_br, start=start, end=end, interval='1mo')['Close']
[*********************100%***********************]  4 of 4 completed
/Users/alexandre.sabino/git/fiap-tech-challenge-genetic-algorithm/app/collect_prices.py:22: FutureWarning: YF.download() has changed argument auto_adjust default to True
  usd_brl = yf.download("USDBRL=X", start=start, end=end, interval='1mo')['Close']
[*********************100%***********************]  1 of 1 completed

In [29]:
all_prices_usd.head()

Ticker,BIL,BTC-USD,IAU,IVV,TLT,BOVA11.SA,IMAB11.SA,SMAL11.SA,XFIX11.SA
Date,,,,,,,,,
2021-01-01,80.369820,33114.359375,35.099998,348.209198,133.381897,20.246117,14.869615,23.806035,1.875183
2021-02-01,80.361046,45137.769531,32.880001,357.816101,125.589607,18.863441,14.259683,22.716879,1.840074
2021-03-01,80.352280,58918.832031,32.520000,372.859009,118.996880,19.408830,13.763949,23.243121,1.758611
2021-04-01,80.352280,57750.175781,33.700001,393.921082,121.945923,21.437673,15.165655,26.328611,1.902031
2021-05-01,80.343483,37332.855469,36.259998,396.526062,121.936546,23.148149,15.544101,28.514701,1.943490

In [30]:
all_prices_usd.columns

Index(['BIL', 'BTC-USD', 'IAU', 'IVV', 'TLT', 'BOVA11.SA', 'IMAB11.SA',
       'SMAL11.SA', 'XFIX11.SA'],
      dtype='object', name='Ticker')

In [35]:
all_prices_usd = all_prices_usd.dropna()
returns = all_prices_usd.pct_change()
returns.head()

Ticker,BIL,BTC-USD,IAU,IVV,TLT,BOVA11.SA,IMAB11.SA,SMAL11.SA,XFIX11.SA
Date,,,,,,,,,
2021-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-02-01,-0.000109,0.363088,-0.063248,0.027589,-0.058421,-0.068293,-0.041019,-0.045751,-0.018723
2021-03-01,-0.000109,0.305311,-0.010949,0.042041,-0.052494,0.028912,-0.034765,0.023165,-0.044272
2021-04-01,0.000000,-0.019835,0.036285,0.056488,0.024783,0.104532,0.101839,0.132749,0.081553
2021-05-01,-0.000109,-0.353546,0.075964,0.006613,-0.000077,0.079788,0.024954,0.083031,0.021797

In [38]:
returns = returns.dropna()
returns.head()

Ticker,BIL,BTC-USD,IAU,IVV,TLT,BOVA11.SA,IMAB11.SA,SMAL11.SA,XFIX11.SA
Date,,,,,,,,,
2021-02-01,-0.000109,0.363088,-0.063248,0.027589,-0.058421,-0.068293,-0.041019,-0.045751,-0.018723
2021-03-01,-0.000109,0.305311,-0.010949,0.042041,-0.052494,0.028912,-0.034765,0.023165,-0.044272
2021-04-01,0.000000,-0.019835,0.036285,0.056488,0.024783,0.104532,0.101839,0.132749,0.081553
2021-05-01,-0.000109,-0.353546,0.075964,0.006613,-0.000077,0.079788,0.024954,0.083031,0.021797
2021-06-01,-0.000218,-0.061394,-0.070325,0.019614,0.044219,0.061975,0.040604,0.061622,0.022825

In [41]:
print(returns.std())

Ticker
BIL          0.003007
BTC-USD      0.181535
IAU          0.040658
IVV          0.046705
TLT          0.044928
BOVA11.SA    0.075990
IMAB11.SA    0.044085
SMAL11.SA    0.090758
XFIX11.SA    0.047336
dtype: float64