In [1]:
from app.collect_prices import collect_prices

In [2]:
all_prices_usd = collect_prices()

/Users/alexandre.sabino/git/fiap-tech-challenge-genetic-algorithm/app/collect_prices.py:29: FutureWarning: YF.download() has changed argument auto_adjust default to True
  prices_usa = yf.download(tickers_usa, start=start, end=end, interval='1mo')['Close']
[*********************100%***********************]  5 of 5 completed
/Users/alexandre.sabino/git/fiap-tech-challenge-genetic-algorithm/app/collect_prices.py:20: FutureWarning: YF.download() has changed argument auto_adjust default to True
  prices_br = yf.download(tickers_br, start=start, end=end, interval='1mo')['Close']
[*********************100%***********************]  4 of 4 completed
/Users/alexandre.sabino/git/fiap-tech-challenge-genetic-algorithm/app/collect_prices.py:22: FutureWarning: YF.download() has changed argument auto_adjust default to True
  usd_brl = yf.download("USDBRL=X", start=start, end=end, interval='1mo')['Close']
[*********************100%***********************]  1 of 1 completed

In [3]:
all_prices_usd.head()

Ticker,BIL,BTC-USD,IAU,IVV,TLT,BOVA11.SA,IMAB11.SA,SMAL11.SA,XFIX11.SA
Date,,,,,,,,,
2021-01-01,80.101730,33114.359375,35.099998,348.209198,132.886124,20.246117,14.869615,23.806035,1.875183
2021-02-01,80.092979,45137.769531,32.880001,357.816101,125.122795,18.863441,14.259683,22.716879,1.840074
2021-03-01,80.084229,58918.832031,32.520000,372.859039,118.554543,19.408830,13.763949,23.243121,1.758611
2021-04-01,80.084229,57750.175781,33.700001,393.921143,121.492714,21.437673,15.165655,26.328611,1.902031
2021-05-01,80.075493,37332.855469,36.259998,396.526001,121.483353,23.148149,15.544101,28.514701,1.943490

In [4]:
all_prices_usd.columns

Index(['BIL', 'BTC-USD', 'IAU', 'IVV', 'TLT', 'BOVA11.SA', 'IMAB11.SA',
       'SMAL11.SA', 'XFIX11.SA'],
      dtype='object', name='Ticker')

In [5]:
all_prices_usd = all_prices_usd.dropna()
returns = all_prices_usd.pct_change()
returns.head()

Ticker,BIL,BTC-USD,IAU,IVV,TLT,BOVA11.SA,IMAB11.SA,SMAL11.SA,XFIX11.SA
Date,,,,,,,,,
2021-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-02-01,-0.000109,0.363088,-0.063248,0.027589,-0.058421,-0.068293,-0.041019,-0.045751,-0.018723
2021-03-01,-0.000109,0.305311,-0.010949,0.042041,-0.052494,0.028912,-0.034765,0.023165,-0.044272
2021-04-01,0.000000,-0.019835,0.036285,0.056488,0.024783,0.104532,0.101839,0.132749,0.081553
2021-05-01,-0.000109,-0.353546,0.075964,0.006613,-0.000077,0.079788,0.024954,0.083031,0.021797

In [6]:
returns = returns.dropna()
returns.head()

Ticker,BIL,BTC-USD,IAU,IVV,TLT,BOVA11.SA,IMAB11.SA,SMAL11.SA,XFIX11.SA
Date,,,,,,,,,
2021-02-01,-0.000109,0.363088,-0.063248,0.027589,-0.058421,-0.068293,-0.041019,-0.045751,-0.018723
2021-03-01,-0.000109,0.305311,-0.010949,0.042041,-0.052494,0.028912,-0.034765,0.023165,-0.044272
2021-04-01,0.000000,-0.019835,0.036285,0.056488,0.024783,0.104532,0.101839,0.132749,0.081553
2021-05-01,-0.000109,-0.353546,0.075964,0.006613,-0.000077,0.079788,0.024954,0.083031,0.021797
2021-06-01,-0.000219,-0.061394,-0.070325,0.019614,0.044219,0.061975,0.040604,0.061622,0.022825

In [7]:
print(returns.std())

Ticker
BIL          0.002946
BTC-USD      0.179917
IAU          0.040290
IVV          0.046454
TLT          0.044590
BOVA11.SA    0.075410
IMAB11.SA    0.043825
SMAL11.SA    0.090036
XFIX11.SA    0.047088
dtype: float64

In [1]:
from app.population_generator import PopulationGeneratorWithHotStart
from app.collect_prices import collect_prices
import pandas as pd
import itertools

In [2]:
df = collect_prices().dropna()

/Users/alexandre.sabino/git/fiap-tech-challenge-genetic-algorithm/app/collect_prices.py:29: FutureWarning: YF.download() has changed argument auto_adjust default to True
  prices_usa = yf.download(tickers_usa, start=start, end=end, interval='1mo')['Close']
[*********************100%***********************]  5 of 5 completed
/Users/alexandre.sabino/git/fiap-tech-challenge-genetic-algorithm/app/collect_prices.py:20: FutureWarning: YF.download() has changed argument auto_adjust default to True
  prices_br = yf.download(tickers_br, start=start, end=end, interval='1mo')['Close']
[*********************100%***********************]  4 of 4 completed
/Users/alexandre.sabino/git/fiap-tech-challenge-genetic-algorithm/app/collect_prices.py:22: FutureWarning: YF.download() has changed argument auto_adjust default to True
  usd_brl = yf.download("USDBRL=X", start=start, end=end, interval='1mo')['Close']
[*********************100%***********************]  1 of 1 completed

In [3]:
gen = PopulationGeneratorWithHotStart()

In [4]:
all_individuals = gen.initial(df)

all_assets = [i.assets for i in all_individuals]
df_population = pd.DataFrame(all_assets)

In [5]:
df_population.tail()
df = df_population.copy()

In [6]:
# bin_labels = ['Faixa 1', 'Faixa 2', 'Faixa 3', 'Faixa 4', 'Faixa 5', 'Faixa 6', 'Faixa 7', 'Faixa 8', 'Faixa 9']
bin_labels = ['Faixa 1', 'Faixa 2', 'Faixa 3', 'Faixa 4', 'Faixa 5']
for col in df.columns:
    df[f'{col}_bin'] = pd.cut(df[col],
                               bins=len(bin_labels),
                               labels=bin_labels)

df.filter(like='_bin').head()

,TLT_bin,SMAL11.SA_bin,BIL_bin,XFIX11.SA_bin,BOVA11.SA_bin,IMAB11.SA_bin,IVV_bin,IAU_bin,BTC-USD_bin
0,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 3,Faixa 3,Faixa 5
1,Faixa 1,Faixa 1,Faixa 5,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 5,Faixa 1
2,Faixa 1,Faixa 3,Faixa 2,Faixa 1,Faixa 3,Faixa 1,Faixa 2,Faixa 2,Faixa 1
3,Faixa 1,Faixa 1,Faixa 2,Faixa 2,Faixa 2,Faixa 1,Faixa 4,Faixa 4,Faixa 1
4,Faixa 1,Faixa 1,Faixa 3,Faixa 1,Faixa 4,Faixa 3,Faixa 1,Faixa 1,Faixa 4

In [7]:
df[df['TLT_bin'] == 'Faixa 1']['TLT']

0      0.020000
1      0.046510
2      0.020000
3      0.064053
4      0.020000
         ...
479    0.020000
484    0.050705
487    0.020000
495    0.020077
497    0.020000
Name: TLT, Length: 215, dtype: float64

In [8]:
df.drop(columns=df_population.columns, inplace=True)

In [9]:
df['IAU_bin'].value_counts()

IAU_bin
Faixa 1    250
Faixa 3     87
Faixa 2     84
Faixa 4     55
Faixa 5     24
Name: count, dtype: int64

In [18]:
for col in df.columns:
    print(df[col].value_counts())

TLT_bin
Faixa 1    317
Faixa 2     62
Faixa 4     47
Faixa 3     42
Faixa 5     32
Name: count, dtype: int64
SMAL11.SA_bin
Faixa 1    340
Faixa 3     56
Faixa 2     46
Faixa 4     29
Faixa 5     29
Name: count, dtype: int64
BIL_bin
Faixa 1    314
Faixa 2     62
Faixa 3     60
Faixa 4     41
Faixa 5     23
Name: count, dtype: int64
XFIX11.SA_bin
Faixa 1    316
Faixa 2     59
Faixa 4     45
Faixa 3     42
Faixa 5     38
Name: count, dtype: int64
BOVA11.SA_bin
Faixa 1    335
Faixa 4     51
Faixa 2     49
Faixa 3     42
Faixa 5     23
Name: count, dtype: int64
IMAB11.SA_bin
Faixa 1    322
Faixa 2     60
Faixa 3     49
Faixa 4     38
Faixa 5     31
Name: count, dtype: int64
IVV_bin
Faixa 1    305
Faixa 2     64
Faixa 5     45
Faixa 3     43
Faixa 4     43
Name: count, dtype: int64
IAU_bin
Faixa 1    316
Faixa 2     55
Faixa 3     51
Faixa 4     46
Faixa 5     32
Name: count, dtype: int64
BTC-USD_bin
Faixa 1    304
Faixa 2     68
Faixa 3     50
Faixa 4     40
Faixa 5     38
Name: count, dtype: int64

In [19]:
all_combinations_itertools = itertools.product(bin_labels, repeat=len(df.columns))
df_combinations = pd.DataFrame(all_combinations_itertools, columns=df.columns)

In [20]:
print(f"\n--- Total de Combinações Possíveis: {len(df_combinations)} ---")
print("As 5 primeiras combinações possíveis:")
df_combinations.head()

--- Total de Combinações Possíveis: 1953125 ---
As 5 primeiras combinações possíveis:

,TLT_bin,SMAL11.SA_bin,BIL_bin,XFIX11.SA_bin,BOVA11.SA_bin,IMAB11.SA_bin,IVV_bin,IAU_bin,BTC-USD_bin
0,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1
1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 2
2,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 3
3,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 4
4,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 5

In [21]:
df_exists_combinations = df[df.columns].drop_duplicates()

print(f"\n--- Total de Combinações Existentes no DataFrame: {len(df_exists_combinations)} ---")
df_exists_combinations.head()

--- Total de Combinações Existentes no DataFrame: 475 ---

,TLT_bin,SMAL11.SA_bin,BIL_bin,XFIX11.SA_bin,BOVA11.SA_bin,IMAB11.SA_bin,IVV_bin,IAU_bin,BTC-USD_bin
0,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 2,Faixa 3,Faixa 5
1,Faixa 1,Faixa 1,Faixa 5,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 4,Faixa 1
2,Faixa 3,Faixa 2,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 5,Faixa 1,Faixa 1
3,Faixa 5,Faixa 1,Faixa 1,Faixa 3,Faixa 1,Faixa 1,Faixa 3,Faixa 1,Faixa 1
4,Faixa 1,Faixa 1,Faixa 1,Faixa 4,Faixa 1,Faixa 1,Faixa 1,Faixa 3,Faixa 4

In [23]:
on_join = ['TLT_bin', 'SMAL11.SA_bin', 'BIL_bin', 'XFIX11.SA_bin',
               'BOVA11.SA_bin', 'IMAB11.SA_bin', 'IAU_bin', 'IVV_bin', 'BTC-USD_bin']

df_merged = df_combinations.merge(df_exists_combinations, on=on_join, how='left', indicator=True)

df_pending_combinations = df_merged[df_merged['_merge'] == 'left_only']

df_pending_combinations = df_pending_combinations.drop(columns='_merge')


print(f"\n--- Total de Combinações Faltantes: {len(df_pending_combinations)} ---")
print("As 10 primeiras combinações faltantes:")
df_pending_combinations.head(10)

--- Total de Combinações Faltantes: 1953033 ---
As 10 primeiras combinações faltantes:

,TLT_bin,SMAL11.SA_bin,BIL_bin,XFIX11.SA_bin,BOVA11.SA_bin,IMAB11.SA_bin,IVV_bin,IAU_bin,BTC-USD_bin
0,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1
1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 2
2,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 3
3,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 4
4,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 5
5,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 2,Faixa 1
6,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 2,Faixa 2
7,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 2,Faixa 3
8,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 2,Faixa 4
10,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 1,Faixa 3,Faixa 1